# Generated by Django 4.1.5 on 2023-02-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('isElectric', models.BooleanField()),
                ('color', models.CharField(max_length=15)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'guitar',
            },
        ),
    ]
