# Generated by Django 4.1.5 on 2023-02-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitar',
            name='isElectric',
        ),
    ]
