# Generated by Django 4.1.5 on 2023-02-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_shop', '0003_alter_guitar_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='isElectric',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
