# Generated by Django 4.1.5 on 2023-02-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_shop', '0005_alter_guitar_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='isElectric',
            field=models.BinaryField(),
        ),
    ]
