# Generated by Django 4.1.5 on 2023-02-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_shop', '0006_alter_guitar_iselectric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitar',
            name='isElectric',
        ),
        migrations.AddField(
            model_name='guitar',
            name='material',
            field=models.CharField(default='wood', max_length=100),
            preserve_default=False,
        ),
    ]
