# Generated by Django 4.1.5 on 2023-02-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_shop', '0007_remove_guitar_iselectric_guitar_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='gid',
            field=models.IntegerField(unique=True),
        ),
    ]
