# Generated by Django 4.1.5 on 2023-02-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_shop', '0008_alter_guitar_gid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitar',
            name='material',
        ),
        migrations.AddField(
            model_name='guitar',
            name='isElectric',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
