# Generated by Django 4.1.5 on 2023-02-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_shop', '0009_remove_guitar_material_guitar_iselectric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitar',
            name='id',
        ),
        migrations.AlterField(
            model_name='guitar',
            name='gid',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
